name: Build (helper)

permissions:
  contents: read

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CC: clang
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  modern-default:
    # Test modern compilers on standard platforms on Linux.
    name: "${{ matrix.target }} - ${{ matrix.rust }} (default configuration)"
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_DEV_SPLIT_DEBUGINFO: ${{ matrix.debug_info }}
      RUSTFLAGS: -D warnings -Clink-arg=-Wl,--compress-debug-sections=zlib
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        rust:
          - stable
          - nightly
        debug_info:
          - packed
        include:
          # RISCV doesn't work with split debug info (see rust-lang/rust#110224)
          - target: riscv64gc-unknown-linux-gnu
            rust: stable
            debug_info: off
          - target: riscv64gc-unknown-linux-gnu
            rust: nightly
            debug_info: off
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Print environment info
        run: |
          echo "# Rust"
          rustc -Vv
          echo "# Cargo"
          cargo -Vv
          echo "# GCC"
          gcc -v
          echo "# Clang"
          clang -v
          echo "# Ld"
          ld -v
      - name: Install cross
        uses: taiki-e/install-action@ad95d4e02e061d4390c4b66ef5ed56c7fee3d2ce # v2.58.17
        with:
          tool: cross@latest
      # TODO: Cache is broken for cross compiles, figure this out
      #- name: Cache builds
      #  uses: Swatinem/rust-cache@v2.7.8
      #  with:
      #    key: ${{ matrix.target }}-${{ matrix.rust }}
      - name: Cross compile binary
        run: cross build --release --locked --target ${{ matrix.target }} --verbose
      - name: Cross compile tests
        run: cross test --release --no-run --locked --target ${{ matrix.target }} --verbose
      - name: Cross test
        run: cross test --release --locked --target ${{ matrix.target }} --verbose
      - name: Compress binary
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        run: |
          mkdir perf-to-statemap
          cp target/${{ matrix.target }}/release/perf-to-statemap perf-to-statemap/
          if [[ -f target/${{ matrix.target }}/release/perf-to-statemap.dwp ]]; then
            # No split release info for RISCV
            cp target/${{ matrix.target }}/release/perf-to-statemap.dwp perf-to-statemap/
          fi
          tar cf perf-to-statemap.tar perf-to-statemap
          zstd -T0 -6 perf-to-statemap.tar
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        with:
          name: perf-to-statemap_${{ matrix.target }}.tar.zst
          path: perf-to-statemap.tar.zst
          retention-days: 7
      - name: Clean up temporary items
        run: |
          rm -rf perf-to-statemap perf-to-statemap.tar perf-to-statemap.tar.zst

  configurations:
    # Test non-standard configurations, MSRV and Rust versions
    name: "Test: \"${{ matrix.features }}\" (Linux), Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - --all-features
        rust:
          - 1.89.0
          - stable
          - nightly
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal  ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Get cargo-binstall
        run: |
          curl -L https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -zxf - && mv cargo-binstall $HOME/.cargo/bin/
      - name: Cache builds
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - name: Compile
        run: cargo test --locked ${{ matrix.features }} --verbose --no-run
      - name: Test
        run: cargo test --locked ${{ matrix.features }} --verbose
    env:
      # Warnings are ok for now here due to private APIs that will be public in the future.
      RUSTFLAGS: ""
